clone:
  depth: full
definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
pipelines:
  default: # default steps for features
    - step:
        image: maven:3.5.2-jdk-8
        name: Build feature
        caches:
          - sonar
        script:
          - mvn -s settings.xml -V -B clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        artifacts:
          - target/application.zip
    - step:
        image: python:3.6.4
        name: Deploy to Staging
        deployment: staging
        trigger: manual
        script:
          - pip3 install boto3==1.3.0
          - export DEPLOYMENT_GROUP_NAME=staging
          - python3 codedeploy_deploy.py
  branches:
    master: # steps for RELEASE versions
      - step:
          image: maven:3.5.2-jdk-8
          name: Build master branch
          caches:
            - sonar
          script:
            - mvn -V -B -P production -s settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar deploy
          artifacts:
            - target/application.zip
      - step:
          image: python:3.6.4
          name: Deploy to production
          deployment: production
          script:
            - pip3 install boto3==1.3.0
            - export DEPLOYMENT_GROUP_NAME=production
            - python3 codedeploy_deploy.py
    develop: # steps for development SNAPSHOT version
      - step:
          image: maven:3.5.2-jdk-8
          name: Build development branch
          caches:
            - sonar
          script:
            - mvn -V -B -s settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar deploy
          artifacts:
            - target/application.zip
      - step:
          image: python:3.6.4
          name: Deploy to staging
          deployment: staging
          script:
            - pip3 install boto3==1.3.0
            - export DEPLOYMENT_GROUP_NAME=staging
            - python3 codedeploy_deploy.py
    release/*: # steps for development release branches
      - step:
          image: maven:3.5.2-jdk-8
          name: Build release candidate
          caches:
            - sonar
          script:
            - mvn -s settings.xml -V -B clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          artifacts:
            - target/application.zip
      - step:
          image: python:3.6.4
          name: Deploy to Staging
          deployment: staging
          trigger: manual
          script:
            - pip3 install boto3==1.3.0
            - export DEPLOYMENT_GROUP_NAME=staging
            - python3 codedeploy_deploy.py